config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'todos#index'
  resources :pages
  resources :todos

  get '/about', to: 'pages#about'
  get '/help', to: 'pages#help'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def hello
    @todos = Todo.last(5).reverse
  end

  def about
  end

  def help
  end

  def create
    Todo.create(name: params[:todo][:name], description: params[:todo][:description])
    redirect_to '/'
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  # before the given actions, run the set_todo method
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  def index
    @todos = Todo.last(5).reverse
  end

  def new
    @todo = Todo.new
  end

  def show
  end

  def edit
  end

  def destroy
    @todo.destroy
    flash[:notice] = "Todo was successfully destroyed!"

    redirect_to todos_path
  end

  def update
    if @todo.update(todo_params)
      flash[:notice] = "Todo was successfully updated!"
      redirect_to todo_path(@todo)
    else
      render 'edit'
    end
  end

  def create
    # Using rails 4 "strong params" to whitelist only certain params for this route
    # when a request is made here, we grab name and description from params, and put them in .new

    @todo = Todo.new(todo_params)
    # @todo will have errors @todo.errors.full_messages if it doesnt work.
    # Todo.create(name: params[:todo][:name], description: params[:todo][:description])
    # puts Todo.create(name: params[:todo][:name], description: params[:todo][:description])

    if @todo.save
      # Create a flash message
      flash[:notice] = "Todo was created successfully!"
      redirect_to todo_path(@todo)
    else
      render "new"
    end

  end


  private
  # only permit name & description parameters during this request.
  # this is good when you want to just slap todo_params in a .update method or something,
  # and not have to worry about hackers putting in url params to screw up your db
  def todo_params
    params.require(:todo).permit(:name, :description)
  end

  def set_todo
    @todo = Todo.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<ul>
  <% flash.each do |name, message| %>
    <li><%= message %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DraculasRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/messages" %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>About</title>
  </head>
  <body>
  <h1>About Page</h1>
  </body>
</html>

app/views/pages/hello.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Hello</title>
  </head>
  <body>
    <h1>Hello, rails!</h1>

    <ul class="todos-list">
      <% for todo in @todos %>
        <li>
          <p>Name: <%= todo.name %></p>
          <p>Description: <%= todo.description %></p>
        </li>
      <% end %>
    </ul>

    <%= form_for :todo, url: pages_path do |f| %>
      Name: <%= f.text_field :name %><br />
      Description : <%= f.text_field :description %><br />
    <%= f.submit %>
    <% end %>
  </body>
</html>

app/views/pages/help.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Help</title>
  </head>
  <body>
    <h1>Help Page</h1>
    <p>Help to learn rails on it's way!</p>
  </body>
</html>

app/views/todos/_form.html.erb
<% if @todo.errors.any? %>
  <h2>The following errors prevented the todo from being saved</h2>
  <ul>
    <% @todo.errors.full_messages.each do |error| %>
    <li><%= error %></li>
    <% end %>
  </ul>
<% end %>


<%= form_for @todo do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
<%= f.submit %>
<% end %>

<%= link_to "View Todos", todos_path %>

app/views/todos/edit.html.erb
<h1>Edit a todo</h1>

<%= render "form" %>

app/views/todos/index.html.erb
<p> <%= link_to "Create a todo", new_todo_path %> </p>

<h1>Todo List</h1>

<table class="todos-list">
  <tr>
    <th>Name</th>
    <th>Description</th>
  </tr>
  <% for todo in @todos %>
    <tr>
      <td><%= todo.name %></yd>
      <td><%= todo.description %></td>
      <td> <%= link_to "Edit", edit_todo_path(todo) %></td>
      <td><%= link_to "Show", todo_path(todo) %></td>
      <td><%= link_to "Delete", todo_path(todo), method: "delete", data: { confirm: "Are you sure?" } %></td>
    </tr>
  <% end %>
</table>

<%= link_to "Add a todo", todo_path(:new) %>

app/views/todos/new.html.erb
<h1>Todo List</h1>

<%= render "form" %>

app/views/todos/show.html.erb
<p><%= @todo.name %></p>
<p><%= @todo.description %></p>

<%= link_to "View Todos", todos_path %>
<%= link_to "Edit this todo", edit_todo_path(@todo) %>